image: node:10.16

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  services:
    - postgres:11.3

  variables:
    POSTGRES_DB: activity-log_test
    POSTGRES_USER: super_node
    POSTGRES_PASSWORD: "node@node"

  script:
    - npm install
    - npx knex migrate:latest --env ci
    - npm run lint
