language: node_js
node_js:
  - 10.16

services:
  - docker
  - postgresql
  - redis-server

addons:
  postgresql: "11"

env:
  jobs:
    - CACHER: redis://localhost:6379

before_install:
  - psql -c 'create database activity_log_test;' -U postgres
  - npm install
  - npx knex migrate:latest --env ci
  - npm run lint
  - npm run test-ci

