version: "3.7"
services:
  activity-log-service:
    env_file: dev.docker-compose.env
    container_name: activity-log-service
    build:
      context: ../
      dockerfile: Dockerfile
    entrypoint: docker/entrypoint.sh
    networks:
      dev_network:
networks:
  dev_network:
    external: true

