version: "3.7"
services:
  activity-log-db:
    image: "postgres:11.3"
    environment:
      POSTGRES_DB: activity-log_dev
      POSTGRES_USER: activity-log_dev
      POSTGRES_PASSWORD: node@node
    container_name: "upload-node-postgres"
    ports:
      - 5432:5432
    networks:
      dev_network:
  activity-log-service:
    env_file: dev.docker-compose.env
    container_name: "activity-log-service"
    build:
      context: ../
      dockerfile: Dockerfile
    entrypoint: docker/entrypoint.sh
    networks:
      dev_network:
networks:
  dev_network:
    external: true
