version: "3.7"
services:
  activity-log-service:
    env_file: dev.docker-compose.env
    container_name: activity-log-service
    build:
      context: ../
      dockerfile: Dockerfile
    entrypoint: docker/entrypoint.sh
    networks:
      dev_network:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
      container_name: elasticsearch
      environment:
        - node.name=elasticsearch
        - cluster.name=es-docker-cluster
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
networks:
  dev_network:
    external: true
volumes:
  elasticsearch-data:
    driver: local
